### ISSUE TITLE
Compile errors when building Samples.csproj with VS2019

### ISSUE THREAD

**Issue by griestopf** [WaveEngine/WebGL.NET#3] opened 2019-05-29 08:10 UTC
How to reproduce:
1. Open WebGL.NET.sln in Visual Studio IDE 2019 (Enterprise Edition used here)
2. Build the contained Samples.csproj 
**Result**
The type `JSObject`  (implemented in WebAssembly.Bindings.dll referenced via NuGet) is unknown in Samples.csproj. Any occurrence of the type name in Sample.csproj's sources generates a compile error.

**Additional observations**
- All other projects contained in WebGL.NET.sln referencing WebAssembly.Bindings and using `JSObject` (e.g. WebGLDotNET.csproj) successfully build in VS2019
- Samples.csproj builds with VS2017
- Changing the first XML-Line of Samples.csproj from
    ```xml
    <Project Sdk="Mono.WebAssembly.Sdk">
    ```
   to
    ```xml
    <Project Sdk="Microsoft.NET.Sdk">
    ```
    makes Samples.csproj build successfully in VS2019. The output does not run in a browser though, because supporting WASM files are not copied/generated in the output.

**Comment by kjpou1** [comment] 2019-06-03 04:11
There is a fix in the pipeline for VS2019 Mac for this.

**Comment by griestopf** [comment] 2019-06-04 08:12
Thanks for your answer. I don't have any experience with VS on Mac, I also have no Mac at hand. Any hint how to apply your advice to VS2019 on Windows?
Thank you.

**Comment by jacano** [comment] 2019-06-04 22:43
Hi @griestopf 
I have a clean installation of Visual Studio 2019 Community in Windows and I'm unable to reproduce the compile error in the JSObject type.
I'm also using VS2019 in Azure DevOps for CI on Windows without issues. I guess it could be on your side.

For CI I use build.sh also in Windows, via msys2 from Git for Windows. Why don't you give a try to this build script?
In Windows you have to run ./scripts/install_env_windows.sh from project root before running ./build.sh and ensure you enabled Win10 Developer Mode.

**Comment by jacano** [comment] 2019-06-14 12:16
@griestopf

**Comment by MarcosCobena** [comment] 2019-06-24 07:43
Hi all,

Let me please close this issue for now, we can reopen it if needed.

Thanks,

—Marcos

**Closed by MarcosCobena** 2019-06-24 07:43 UTC
